- src/GlobalStyles.tsx
- src/components/Buttons/index.tsx
- src/components/Buttons/styles.tsx
- src/components/Header/index.tsx
- src/components/Link/styles.tsx
- src/components/ModalForm/index.tsx
- src/components/ModalForm/styles.tsx
- src/components/SearchBar/index.tsx
- src/components/SearchBar/styles.tsx
- src/components/SignUpForm/index.tsx
- src/components/SignUpForm/styles.tsx
- src/pages/HomePage/components/CTA/index.tsx
- src/pages/HomePage/components/CTA/styles.tsx
- src/pages/HomePage/components/TitleCard/index.tsx
- src/pages/HomePage/components/TitleCard/styles.tsx
- src/stories/Footer.stories.tsx
- src/stories/Header.stories.tsx
> yarn lint:fix

- package.json
- src/ClientProvider/axiosConfig.ts
- src/ClientProvider/clientProvider.ts
- src/ClientProvider/index.ts
- src/components/ModalForm/index.tsx
- src/components/ModalForm/styles.tsx
- src/components/SignUpForm/index.tsx
- src/main.tsx
- src/pages/HomePage/components/CTA/index.tsx
- yarn.lock
> feat: use API to create user

- .eslintrc.json
- README.md
- src/ClientProvider/axiosConfig.ts
- src/ClientProvider/clientProvider.ts
- src/Layout.tsx
- src/components/Footer/index.tsx
- src/components/Header/index.tsx
- src/components/ModalForm/index.tsx
- src/components/SearchBar/index.tsx
- src/components/SignUpForm/index.tsx
- src/components/Uploader/index.tsx
- src/declaration.d.ts
- src/pages/HomePage/components/Carousel/index.tsx
- src/pages/HomePage/components/Carousel/styles.tsx
- src/pages/HomePage/components/TitleCard/index.tsx
- src/pages/HomePage/index.tsx
- src/stories/Footer.stories.tsx
- src/stories/Header.stories.tsx
Linting now includes TS type errors.
I also fixed most warnings and errors.
Keeping a few more complex ones for another specific PR.
> [LINTING] add typescript type-checking to linting + fix simple errors

- src/components/Buttons/styles.tsx
very small fix on the button because the text wasn't centered
> fix: button is responsive with centered text

- .eslintrc.json
- package.json
- src/ClientProvider/clientProvider.ts
- src/ClientProvider/index.ts
- src/Layout.tsx
- src/components/Buttons/styles.tsx
- src/components/Footer/index.tsx
- src/components/Footer/styles.tsx
- src/components/Header/index.tsx
- src/components/Header/styles.tsx
- src/components/Link/styles.tsx
- src/components/LogOut/index.tsx
- src/components/LoginForm/index.tsx
- src/components/Modal/index.tsx
- src/components/SearchBar/index.tsx
- src/components/SignUpForm/index.tsx
- src/main.tsx
- src/pages/Gardens/components/Banner/index.tsx
- src/pages/Gardens/components/Search/index.tsx
- src/pages/Gardens/components/Search/styles.tsx
- src/pages/Gardens/components/Thumb/index.tsx
- src/pages/Gardens/index.tsx
- src/pages/Gardens/styles.tsx
- src/pages/HomePage/components/CTA/index.tsx
- src/pages/HomePage/components/Carousel/index.tsx
- src/pages/HomePage/components/TitleCard/index.tsx
- src/pages/HomePage/index.tsx
- yarn.lock
#33
Add eslint-simple-import-sort to... sort imports ↕️ 
> Simple imports sort

- src/GlobalStyles.tsx
- src/components/Header/index.tsx
- src/components/Header/styles.tsx
- src/components/LogOut/index.tsx
- src/components/LoginForm/index.tsx
- src/components/SignUpForm/index.tsx
- src/components/SignUpForm/styles.tsx
- src/components/Uploader/index.tsx
- src/components/Uploader/styles.tsx
- src/pages/Gardens/components/Search/index.tsx
- src/pages/Gardens/index.tsx
- src/pages/HomePage/components/CTA/index.tsx
- src/pages/HomePage/components/CTA/styles.tsx
- src/pages/HomePage/index.tsx
- src/utils/user.ts
- src/wordings.tsx
> Feat image upload 

- package.json
- src/components/Pagination/index.tsx
- src/components/Pagination/styles.tsx
- src/pages/Profile/components/CommentSection/Comment/index.tsx
- src/pages/Profile/components/CommentSection/index.tsx
- src/pages/Profile/components/CommentSection/styles.tsx
- src/pages/Profile/index.tsx
- yarn.lock
> Feat profile  comments query

- src/GlobalStyles.tsx
- src/components/Buttons/styles.tsx
- src/components/LoginForm/index.tsx
- src/components/Modal/styles.tsx
- src/components/SearchBar/index.tsx
- src/components/SignUpForm/index.tsx
- src/pages/Gardens/components/Thumb/index.tsx
- src/pages/Gardens/components/Thumb/styles.tsx
- src/pages/HomePage/components/Carousel/index.tsx
- src/pages/HomePage/components/TitleCard/styles.tsx
[37](https://github.com/JardiPotes/front-garden/issues/37)
> chore: remove hasGarden input

- package.json
- src/Layout.tsx
- src/components/Header/index.tsx
- src/components/Header/styles.tsx
- src/components/LogOut/index.tsx
- src/components/SignUpForm/index.tsx
- yarn.lock
[RELATED TICKET](https://github.com/JardiPotes/front-garden/issues/51)
[RELATED TICKET](https://github.com/JardiPotes/front-garden/issues/50)
Add the user profile link to their avatar. 
After logging in, users will be redirected to their profile page.
> chore: add a link to profile page & redirect users after logging in

- src/components/Header/index.tsx
- src/components/LoginForm/index.tsx
- src/utils/user.ts
> fix: redirection

- src/components/Header/index.tsx
- src/components/LoginForm/index.tsx
> Fix redirection

- src/ClientProvider/clientProvider.ts
- src/components/Buttons/index.tsx
- src/components/LoginForm/index.tsx
- src/components/Pagination/index.tsx
- src/components/Pagination/styles.tsx
- src/pages/Profile/components/CommentSection/Comment/index.tsx
- src/pages/Profile/components/CommentSection/Comment/styles.tsx
- src/pages/Profile/components/CommentSection/Form/index.tsx
- src/pages/Profile/components/CommentSection/index.tsx
- src/pages/Profile/index.tsx
> DRAFT (wip) add comment

- src/pages/Messages/components/Preview/index.tsx
- src/pages/Profile/components/UserInfo/Avatar/index.tsx
> fix: messages

- src/pages/Gardens/components/Thumb/index.tsx
- src/pages/Gardens/index.tsx
Fix zipcode badge & render user profile_image dynamically.
> fix: garden thumb zipcode badge & render user img dynamically

- .gitignore
- fileTransformer.ts
- jest.config.json
- package.json
- src/components/LoginForm/index.tsx
- src/components/SignUpForm/styles.tsx
- src/pages/Gardens/components/Search/index.tsx
- src/pages/Gardens/components/Thumb/index.test.tsx
- src/pages/Gardens/components/Thumb/index.tsx
- src/pages/Gardens/index.test.tsx
- src/pages/Gardens/index.tsx
- src/pages/HomePage/index.test.tsx
- src/pages/Messages/components/Conversation/index.tsx
- src/pages/Messages/components/Message/index.test.tsx
- src/pages/Messages/components/Message/index.tsx
- src/pages/Messages/components/Preview/index.test.tsx
- src/pages/Messages/components/Preview/index.tsx
- src/pages/Messages/components/PreviewSection/index.tsx
- src/pages/Profile/components/Gardens/CreateForm/index.tsx
- src/pages/Profile/components/Gardens/CreateForm/styles.tsx
- src/pages/Profile/components/Gardens/CreateForm/uploader.tsx
- src/pages/Profile/components/Gardens/GardenInfo/index.tsx
- src/pages/Profile/components/Gardens/index.test.tsx
- src/pages/Profile/components/UserInfo/Avatar/index.tsx
- src/pages/Profile/components/UserInfo/index.test.tsx
- src/pages/Profile/index.tsx
- src/pages/Profile/stubs.ts
- tsconfig.json
- yarn.lock
Added unit tests on most important components and fixed a few bugs they revealed (mostly typescript errors)
N/A
> Chore improve unit tests

- .gitignore
- README.md
- cypress.config.ts
- cypress.env.exemple.json
- cypress/e2e/jardipotes.spec.cy.ts
- cypress/e2e/spec.cy.ts
- cypress/fixtures/example.json
- cypress/support/commands.ts
- cypress/support/e2e.ts
- package.json
- src/components/Header/index.tsx
- src/components/Header/styles.tsx
- src/components/LogOut/index.tsx
- src/components/LoginForm/index.tsx
- src/components/SignUpForm/index.tsx
- src/pages/Gardens/components/Search/index.tsx
- src/pages/Gardens/components/Thumb/index.tsx
- src/pages/HomePage/components/CTA/index.tsx
- src/pages/Messages/components/Conversation/index.tsx
- src/pages/Messages/components/Message/index.tsx
- src/pages/Profile/components/CommentSection/index.tsx
- src/pages/Profile/components/Gardens/CreateForm/index.tsx
- src/pages/Profile/components/UserInfo/Avatar/index.tsx
- tsconfig.json
- yarn.lock
Implement E2E testing with cypress to see if everything works when the full app is running
> Chore e2e tests

- src/components/Footer/index.tsx
- src/components/Header/index.tsx
- src/main.tsx
- src/pages/Intro/index.tsx
- src/pages/Intro/styles.tsx
- src/pages/WIP/index.tsx
A static page explaining what is jardipotes and what we expect from users
N/A
> feat: intro page

- src/GlobalStyles.tsx
- src/assets/wordings.tsx
- src/components/Button/TransparentButton/index.tsx
- src/components/Button/TransparentButton/styles.tsx
- src/components/Header/index.tsx
- src/components/Header/styles.tsx
- src/components/LoginForm/index.tsx
- src/components/Modal/styles.tsx
- src/components/SignUpForm/index.tsx
- src/components/Wrappers/SpaceBetweenRow/index.tsx
- src/components/Wrappers/SpaceBetweenRow/styles.tsx
- src/main.tsx
- src/pages/Profile/components/CommentSection/Comment/index.tsx
- src/pages/Profile/components/CommentSection/Form/index.tsx
- src/pages/Profile/components/CommentSection/index.tsx
- src/pages/Profile/components/Gardens/CreateForm/index.tsx
- src/pages/Profile/components/Gardens/CreateForm/styles.tsx
- src/pages/Profile/components/Gardens/GardenInfo/components/ConfirmDelete/index.tsx
- src/pages/Profile/components/Gardens/GardenInfo/components/ConfirmDelete/styles.tsx
- src/pages/Profile/components/Gardens/GardenInfo/components/EditForm/index.tsx
- src/pages/Profile/components/Gardens/GardenInfo/index.tsx
- src/pages/Profile/components/Gardens/GardenInfo/styles.tsx
- src/pages/Profile/components/Gardens/index.tsx
- src/pages/Profile/components/UserInfo/Avatar/index.tsx
- src/pages/Profile/components/UserInfo/BioCard/index.tsx
- src/pages/Profile/components/UserInfo/BioCard/styles.tsx
- src/pages/Profile/components/UserInfo/EditForm/index.tsx
- src/pages/Profile/components/UserInfo/index.tsx
- src/pages/Profile/index.tsx
- src/utils/user.ts
> Edit user/gardens info

- cypress/e2e/jardipotes.spec.cy.ts
- cypress/support/commands.ts
- cypress/tsconfig.json
- fileTransformer.cjs
- fileTransformer.js
- fileTransformer.ts
- jest.config.json
- package.json
- src/ClientProvider/axiosConfig.ts
- src/Layout.tsx
- src/components/Header/index.tsx
- src/components/LoginForm/index.tsx
- src/pages/Messages/components/Conversation/index.tsx
- src/pages/Messages/components/Message/index.test.tsx
- src/pages/Messages/components/Message/index.tsx
- src/pages/Messages/components/Preview/index.test.tsx
- src/pages/Messages/components/Preview/index.tsx
- src/pages/Messages/components/PreviewSection/index.tsx
- src/pages/Messages/index.tsx
- src/pages/Profile/components/UserInfo/index.tsx
- src/utils/user.ts
- tsconfig.json
- yarn.lock
> Fix missing test ids

- src/components/Header/styles.tsx
- src/pages/Gardens/components/Thumb/index.test.tsx
- src/pages/Gardens/components/Thumb/index.tsx
- src/pages/Messages/components/Conversation/index.tsx
- src/pages/Messages/components/Message/styles.ts
- src/pages/Messages/components/Preview/index.tsx
- src/pages/Messages/components/PreviewSection/index.tsx
- src/pages/Messages/index.tsx
- src/pages/Messages/styles.ts
- src/pages/Profile/components/CommentSection/Form/index.tsx
- src/pages/Profile/components/SectionHeader/styles.tsx
Various UI fixes : 
- show profile image in garden thumb 
- messenger properly sync 
- improved messenger UI on mobile 
- comment field reinitialize when submitted
- header doesn't break when resizing screen 
> Fix show profile pic in garden thumb
